---
- hosts: raspb3.local
  become: yes
  gather_facts: no
  tasks:
    - name: Install software
      apt:
        name:
          - rsync

    - name: Create folder
      shell: mkdir -p /nfs/client_filesystem

    - name: Rsync required folders
      shell: rsync -xa --progress --exclude /nfs / /nfs/client_filesystem

    - name: Execute commands in sequence
      shell: |
        cd /nfs/client_filesystem
        mount --bind /dev dev
        mount --bind /sys sys
        mount --bind /proc proc
        chroot . /bin/bash -c "rm /etc/ssh/ssh_host_* && dpkg-reconfigure openssh-server"
        umount dev sys proc
      args:
        executable: /bin/bash
    
